name: nodejs-application

on:
  push:
    branches: [ "main", "feature/express-routes" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Build project
        run: npm run build

      - name: Build docker image
        run: docker build -t ${{ vars.DOCKER_USERNAME }}/demo-app .
    
      - name: Image display
        run: docker images

      - name: Run container
        run: docker run -d -p 4000:3000 umamaheswarigude11/demo-app

      - name: Display containers
        run: docker ps -a
    
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
           username: ${{ vars.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_TOKEN }}
    
      - name: Push the image to docker hub
        run: docker push umamaheswarigude11/demo-app
